-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."partners" add column "is_shop_open" boolean
--  null default 'true';
