-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."stocks" add column "stock_type" text
--  not null default 'STATIC';
