-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."order_items" add column "items" jsonb
--  null default jsonb_build_array();
