-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."orders" add column "total_price" float8
--  not null default '0';
