-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."partners" add column "whatsapp_numbers" jsonb
--  null default jsonb_build_array();
