-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."partners" add column "delivery_status" boolean
--  not null default 'false';
