-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."stocks" add column "show_stock" boolean
--  not null default 'false';
