-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."qr_groups" add column "charge_type" text
--  null default 'flat_fee';
