-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."super_admin" add column "role" text
--  null default 'superadmin';
