-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."partners" add column "gst_percentage" numeric
--  null default '0';
